name: AWS SSM ECS Importer
author: Emanuel Oliveira <emanuelflp@gmail.com>
branding:
  icon: upload-cloud
  color: blue
description: Get SSM Parameters from path and inject all in Task Definition JSON File.
inputs:
  ssm-path:
    description: Path in SSM
    required: true
  container-name:
    description: Name of container that you want to add envvars
    required: true
  task-definition:
    description: 'The path to the ECS task definition JSON file'
    required: true
outputs:
  task_definition:
    description: 'The path to the rendered task definition file'
runs:
  using: 'node12'
  main: 'dist/index.js'